#####################
#                   #
#     LOxigenio     #
#                   #
#####################

Super_pulo: true

Permissao: 'loxigenio.usar'

Capacete:
  Item:
    Material: GLASS
    Nome: '&c&lCapacete'
    Lore:
      - " "
      - "&6Teste"
      - " "

Worlds:
  - 'Mundo'

Mensagens:
  Ativado: '&aOxigénio Ativado.'
  Desativado: '&cOxigénio Desativado.'
  Capacete_ja_equipado: '&cJá está com capacete.'
  Capacete_equipado: '&aColocou novamente o seu capacete.'
  Capacete_diferente: '&cPossui um capacete diferente já colocado.'
  Sem_item_mao: '&cVocê não está segurando um capacete.'
  Sem_perm: '&cVocê não possuí permissão.'